<?php


namespace common\widgets;


use common\services\similar\IBuilder;
use yii\base\Widget;

class SimilarFilms extends Widget
{
    public $searchers;

    public $maximum = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!$this->maximum) {
            $this->maximum = 5;
        }
    }

    public function run()
    {
        foreach ($this->searchers as $searcher) {

        }
    }
}