<?php


namespace common\widgets;


use common\essences\Film;
use common\essences\GenreList;
use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\Url;

class SmallGenreListWidget extends Widget
{
    /* @var $film Film*/
    public $film;

    public $count = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!$this->count) {
            $this->count = 3;
        }
    }

    public function run()
    {
        $content = '';
        $genreList = GenreList::from($this->film);
        $genres = $genreList->genres;
        $additionalPart = '';
        if (count($genreList->genres) > $this->count) {
            $genres = array_slice($genres, 0, $this->count);
            $additionalPart = Html::a('...',
                Url::to([$this->film->id.'#genres']) //TODO Контроллер для жанров отдельного фильма
            );
        }

        foreach ($genres as $genre) {
            $content .= Html::a($genre->name,
                Url::to(['/genre/'.$genre->id]), //TODO Контроллер для жанров
            [
                'style' => [
                    'cursor' => 'default'
                ]
            ]) . '</br>';
        }

        return $content . $additionalPart;
    }
}